import Head from "next/head";
import EventList from "../components/Events/EventList";
import { getFeaturedEvents } from "../helper/helper";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <EventList data={props.featuredEvents} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const featuredEventsData = await getFeaturedEvents();

  return {
    props: {
      featuredEvents: featuredEventsData,
    },
    revalidate: 1800,
  };
}
